### ISSUE TITLE
Input Output configuration is one pixel too small

### ISSUE THREAD

**Issue by Chronophylos** [RLNT/minecraft_lazierae2#10]
## Bug Description

The graphic of the Input/Output configuration in the Crystal Engergizer is one pixel smaller in width than the other buttons on the GUI.
![](https://i.nuuls.com/3Jz7e.png)

## Expected Behavior

The graphic should have the same width as the rest of the buttons

## Current Behavior

Its one pixel too small

## Reproduction

Open the Crystal Engergizer GUI

## Versions

- OS version: Linux 5.12.9-arch1-1
- Mod version: 1.16.5-1.1.3

**Comment by DAmNRelentless** [comment]
This is known and also intended.
The textures are taken from the original mod and already had these dimensions.

The main issue here is that each side is configured separately and the inner box must therefor be dividable by 3.
Since the upgrade slot is a regular item slot which is 16x16 pixels (without the borders), there is no good solution for an I/O configuration layout right now.

Unless someone comes up with a better layout and/or a better design, I'd like to keep it like that.
